---
- hosts: all
  become: true

  tasks:
    - name: Stop running container
      command: docker stop simple-devops-container
      ignore_errors: yes

    - name: Remove stopped container
      command: docker rm simple-devops-container
      ignore_errors: yes

    - name: Remover docker image
      command: docker rmi simple-devops-image
      ignore_errors: yes

    - name: Build docker image
      command: docker build -t simple-devops-image .
      args:
        chdir: /opt/docker
    - name: Create container using simple-deveops-image
      command: docker run -d --name simple-devops-container -p 8080:8080 simple-devops-image